# Generated by Django 4.1.3 on 2022-11-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.CharField(max_length=255)),
                ('customer_address', models.CharField(max_length=255)),
                ('order_date', models.DateTimeField()),
                ('shipping_date', models.DateTimeField()),
                ('delivery_date', models.DateTimeField()),
            ],
        ),
    ]
